version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.12
    working_directory: /go/app
    steps:
    - checkout
    - run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg github.com/zegl/kube-score/... -v github.com/zegl/kube-score/...
    - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-release:
    jobs:
    - test
