project_name: kube-score

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64

archives:
  - id: binary
    format: binary

  # A release in archive format is needed for the homebrew release
  - id: default

dockers:
- goos: linux
  goarch: amd64
  binaries:
  - kube-score
  image_templates:
  - "zegl/kube-score:{{ .Tag }}"
  dockerfile: Dockerfile

- goos: linux
  goarch: amd64
  binaries:
  - kube-score
  image_templates:
  - "zegl/kube-score:{{ .Tag }}-helm"
  dockerfile: helm.Dockerfile

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  - name: kube-score
    github:
      owner: kube-score
      name: homebrew-tap
    folder: Formula
    url_template: "https://github.com/zegl/kube-score/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://kube-score.com/"
    install: |
      bin.install "program"
